name: Rectify11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore NuGet Packages
      run: nuget restore Rectify11Installer.sln
    - name: Build Phase2
      run: msbuild Rectify11.Phase2\Rectify11.Phase2.csproj /p:Configuration=Debug /p:platform=x64
    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Debug /p:platform=x64
    - name: Create single exe
      run: Rectify11Installer\ILRepack.exe Rectify11Installer\bin\Debug\Rectify11Installer.exe /out:Rectify11Installer\bin\output\Debug\Rectify11Installer.exe Rectify11Installer\bin\Debug\libmsstyle.dll Rectify11Installer\bin\Debug\TaskDialog.dll
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: Rectify11Installer (x64)
        # A file, directory or wildcard pattern that describes what to upload
        path: Rectify11Installer\bin\output\Debug\Rectify11Installer.exe
