name: Rectify11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v3
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore NuGet Packages
      run: |
        nuget restore Rectify11Installer.sln
        nuget restore Rectify11ControlCenter\Rectify11ControlCenter.sln
    - name: Build R11 Control Centre
      run: msbuild Rectify11ControlCenter\Rectify11ControlCenter.sln /p:Configuration=Release
    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Release /p:platform=x64
    - name: Create single exe
      run: Rectify11Installer\ILRepack.exe Rectify11Installer\bin\Release\Rectify11Installer.exe /out:Rectify11Installer\bin\output\Release\Rectify11Installer.exe Rectify11Installer\bin\Release\libmsstyle.dll Rectify11Installer\bin\Release\TaskDialog.dll 
    - name: Upload Rectify11Installer
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: Rectify11Installer (x64)
        # A file, directory or wildcard pattern that describes what to upload
        path: Rectify11Installer\bin\output\Release\Rectify11Installer.exe
   
